### ISSUE TITLE
Black icon on ExtraActionButton when masque is enabled

### ISSUE THREAD

**Issue by Tonyleila** [StormFX/Masque#33] opened 2018-08-10 00:16 UTC
https://i.imgur.com/lYz3f5m.jpg

Using dominos. The screenshot show a framestack maybe it helps :)

**Comment by StormFX** [comment] 2018-08-10 19:50
Looks to me like the Icon is being placed below the Backdrop. Masque puts the Icon above it, so something else must be affecting it.

**Comment by StormFX** [comment] 2018-08-30 17:03
I've tried to reproduce this and can't. The Extra Action Bar/Button works fine on my side, with no black overlay at all. Given that these are the only two reports I've had of it, I'm guessing you've another add-on installed that's causing it or something else is going on.

You'll need to back up your saved variables files for Domino and Masque and then remove them. Then start the game with ONLY Dominos and Masque enabled. To be sure it's not skin-related, don't use any extra skins.

**Comment by StormFX** [comment] 2019-01-31 19:18
- Closing since I'm unable to reproduce this and it's been awhile.

**Closed** 2019-01-31 19:17 UTC
Labels: Won't Fix
