### ISSUE TITLE
attempt to index local 'Normal' (a nil value)

### ISSUE THREAD

**Issue by SebastianMuskalla** [StormFX/Masque#57] opened 2019-04-07 17:17 UTC
Since Masque 8.1.2-Alpha, I'm getting the following error whenever a buff runs out.

```
Message: Interface\AddOns\Masque\Core\Regions\Normal.lua:50: attempt to index local 'Normal' (a nil value)
Time: Sun Apr  7 19:15:32 2019
Count: 3
Stack: Interface\AddOns\Masque\Core\Regions\Normal.lua:50: attempt to index local 'Normal' (a nil value)
[C]: ?
Interface\AddOns\Masque\Core\Regions\Normal.lua:50: in function <Interface\AddOns\Masque\Core\Regions\Normal.lua:45>
[C]: in function `SetNormalTexture'
Interface\AddOns\PitBull4\Modules\Aura\Controls.lua:220: in function `onDelete'
Interface\AddOns\PitBull4\Controls\Controls.lua:130: in function `Delete'
Interface\AddOns\PitBull4\Modules\Aura\Update.lua:650: in function <Interface\AddOns\PitBull4\Modules\Aura\Update.lua:582>
Interface\AddOns\PitBull4\Modules\Aura\Update.lua:758: in function `UpdateAuras'
Interface\AddOns\PitBull4\Modules\Aura\Aura.lua:77: in function `UpdateFrame'
Interface\AddOns\PitBull4\Modules\Aura\Update.lua:952: in function `OnUpdate'
Interface\AddOns\PitBull4\Modules\Aura\Aura.lua:21: in function <Interface\AddOns\PitBull4\Modules\Aura\Aura.lua:18>

Locals: 
```

**Comment by StormFX** [comment] 2019-04-07 18:15
Did this error not occur in the previous release? Very little has changed in how that particular piece of code is handled. If you haven't, can you install the latest release (8.0.1) and see if it occurs?

**Comment by SebastianMuskalla** [comment] 2019-04-07 19:06
Thanks for the quick reply.

I reinstalled 8.0.1 and the error stopped occurring.

**Comment by StormFX** [comment] 2019-04-07 19:13
Interesting. Did you discover when it occurs? I know it's because PB4 unsets the normal texture in its `OnDelete()` handler, but I need to be able to know how to reproduce the error so I can figure why it's doing it.

**Comment by SebastianMuskalla** [comment] 2019-04-07 19:16
It occurs everytime a buff is removed.

**Comment by StormFX** [comment] 2019-04-07 20:06
Alright. I'll check it when I get home. Thanks for the report.

**Comment by nebularg** [comment] 2019-04-07 20:55
Hello @StormFX, I was just looking into this. The aura widgets are recycled so [my hacky way](https://github.com/nebularg/PitBull4/blob/d32aa5bdc124567b5e963cb452f1d261a99e9194/Modules/Aura/Controls.lua#L214-L220) of disabling Masque from doing anything to the normal texture when a widget is released is doing `widget.__MSQ_NormalTexture = nil` then `widget:SetNormalTexture(nil)`. In [8.0.1](https://github.com/StormFX/Masque/blob/c532eecd6e2b3d7aeebc5613ba015c06cc8be84a/Core/Button.lua#L165) that was fine, not so much in [8.1.2](https://github.com/StormFX/Masque/blob/master/Core/Regions/Normal.lua#L45), which errors because `Normal` is nil and updating my code to use `__MSQ_Normal` it would just push the error further down.

What I want is to be able to do `widget:SetNormalTexture(nil)` without Masque trying to reapply the default skin. My first thought after looking at the new hook was to just set `__MSQ_NormalSkin` to `{ Hide = true }`, but maybe you have a better idea 😝

**Comment by StormFX** [comment] 2019-04-08 01:39
Yeah, I just found the problem. In versions prior to 8.1, _Masque_ would set any layer it couldn't find to `false`. This was actually erroneous because for the `Normal` region, _Masque_ will actually _skip_ that region if it's set to `false`. And with the way skins work, there should almost *always* be a `Normal` region since that's where the majority of the artwork is.

It also turned out that it was causing some issues with other add-ons so I fixed it. _Masque_ no longer sets missing layers to `false`, but add-ons can still force _Masque_ to skip the `Normal` region by explicitly setting it to `false` in the Regions (ButtonData) table. Note that should only be done if absolutely necessary. Eg, in the case of PB4 ([here](https://github.com/nebularg/PitBull4/blob/d32aa5bdc124567b5e963cb452f1d261a99e9194/Modules/Aura/Controls.lua#L186-L192)):

```lua
		group:AddButton(control, {
			Icon = control.texture,
			Normal = false, -- Explicitly set this to false to disable it.
			Cooldown = control.cooldown,
			Border = control.border,
			-- Count = control.count_text,
			-- Duration = control.cooldown_text,
		})
```

Interestingly, this particular issue has brought to light other problems, one of which you touched on: That _Masque_ will still be hooked after a button's been removed from a group. I'm debating on whether to use AceHook-3.0 so I can use its "unhook" capabilities or just throwing another boolean into the button's table and having all hooks check for it before executing. It should also check for `nil` on that texture before trying to call its methods, of course.

**Comment by StormFX** [comment] 2019-04-08 01:51
While you're here: I'm not sure if you've read the change log for the alpha, but there's some significant changes. Most notably, when you add a button to a group, you'll want to specify the type of button (third parameter), because that tells _Masque_ which regions to look for. You can also tell _Masque_ to skip search for any missing regions (fourth parameter). Assuming I deal with the hook issue and using the relevant code above, you'd end up with something like:

```lua
		group:AddButton(control, {
			Icon = control.texture,
			Cooldown = control.cooldown,
			Border = control.border,
			-- Count = control.count_text,
			-- Duration = control.cooldown_text,
		}, "Aura", true) -- Note the additional parameters.
```

The third parameter, `"Type"`, can be either `"Aura"`, `"Defuff"` or `"Enchant"` (they use different default textures). The fourth, `Strict` will force _Masque_ to skip missing regions, if set to `true`.

**Comment by StormFX** [comment] 2019-04-08 04:24
I've added an alpha that should fix both the error and the issues you're having, @nebularg.

**Comment by nebularg** [comment] 2019-04-08 05:51
Thanks, I knew about `Normal = false` and saw the new type stuff, but, skipping the normal texture would make most skins look weird  :unamused: It's working now without any changes, but for some reason the included skins (Classic, Zoomed, etc) are broken. Don't have the issue with other addons and they work in 8.0.1 😕 

Classic: ![Classic](https://i.imgur.com/n8lhqda.jpg) PitBull ![PitBull](https://i.imgur.com/NXVJ6Ga.jpg)

**Comment by StormFX** [comment] 2019-04-08 07:07
Ah. That's probably because I put the `:SetBlendMode()` call inside the color block, so it's setting the blend mode for that particular texture to "BLEND" instead of "ADD", which shows the whole texture since it doesn't have an alpha channel. I'll fix it in the morning.

**Comment by StormFX** [comment] 2019-04-08 18:39
The new alpha should fix the issues and make it so you don't have to unset anything.

**Comment by Stanzilla** [comment] 2019-04-09 19:51
I'm getting the same/similar error in [nivBuffs](https://github.com/stanzilla/nivbuffs)

```
2x Masque\Core\Group-Group.lua:69: attempt to index local 'Button' (a nil value)
Masque\Core\Group-Group.lua:69: in function `AddButton'
nivBuffs\nivBuffs.lua:1356: in function `?'
nivBuffs\nivBuffs.lua:127: in function <nivBuffs\nivBuffs.lua:127>
```

anything I need to change?

**Comment by StormFX** [comment] 2019-04-09 21:36
Let me install it and see what's going on.

**Comment by StormFX** [comment] 2019-04-10 03:49
@Stanzilla : The latest alpha should get rid of the error, but you still check to make sure the button is nil before passing it. :p

**Comment by Stanzilla** [comment] 2019-04-10 17:31
Awesome, thanks!

**Comment by StormFX** [comment] 2019-04-10 17:44
No problem. That seems to cover everything so far, so I'll close this.

**Comment by Stanzilla** [comment] 2019-04-10 18:28
@StormFX just here then, yeah? https://github.com/Stanzilla/nivBuffs/blob/37985f5f785023965eb033fe1fca1d3ec4066c4c/nivBuffs.lua#L275 I tested with checking that `btn` exists but that still errord.

**Comment by StormFX** [comment] 2019-04-10 19:23
My fault again. Until I push another alpha, go into your local copy of Core\Core.lua and move line 51 up three lines so it looks like this:

```lua
		if type(Button) == "table" then
			Type = Button.GetObjectType and Button:GetObjectType()


			if not Type or not oTypes[Type] then
				Type = nil
			end
			Button.__MSQ_oType = Type
		end
```

I'm assuming you're in the process of updating ninvBuffs, because there's some seriously old code in there :p. For example, _Masque_ now saves the skin settings, so lines 1350, 1353, 1356 and 1369-1375 are all obsolete.

**Closed** 2019-04-10 19:25 UTC
Labels: Bug

**Comment by StormFX** [comment] 2019-04-10 19:26
I've moved this in its own issue. #59
